services:
  auth:
    build: ../services/auth
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: fintechdb_auth
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
