services:
  auth:
    build: ../services/auth
    ports:
      - "8081:8081"
    depends_on:
      - auth-db
      - redis

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: fintechdb_auth
    ports:
      - "5432:5432"
    
  kyc-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: kyc
      POSTGRES_PASSWORD: kyc
      POSTGRES_DB: fintechdb_kyc
    ports:
      - "5433:5432"

  wallet-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: fintechdb_wallet
    ports:
      - "5434:5432"

  redis:
    image: redis:latest
    container_name: fintech_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  kafka:
    image: apache/kafka:latest
    container_name: fintech_kafka
    ports:
      - "9092:9092"
