services:
  - name: auth
    baseURL: "http://localhost:8080/api/v1"
    routes:
      - path: "/auth/register"
        method: "POST"
        servicePath: "/auth/register"
        middlewares: []

      - path: "/auth/login"
        method: "POST"
        servicePath: "/auth/login"
        middlewares: []

      - path: "/auth/refresh"
        method: "POST"
        servicePath: "/auth/refresh"
        middlewares: []

      - path: "/auth/logout"
        method: "POST"
        servicePath: "/auth/logout"
        middlewares: []

  - name: kyc
    baseURL: "http://kyc:9000"
    routes:
      - path: "/kyc/status"
        method: "GET"
        servicePath: "/status"
        middlewares: ["auth", "rateLimit"]
