services:
  - name: auth
    baseURL: "http://localhost:8080/api/v1"
    routes:
      - path: "/auth/register"
        method: "POST"
        servicePath: "/auth/register"
        middlewares: []

      - path: "/auth/login"
        method: "POST"
        servicePath: "/auth/login"
        middlewares: []

      - path: "/auth/refresh"
        method: "POST"
        servicePath: "/auth/refresh"
        middlewares: ["rateLimitAggressive"]

      - path: "/auth/logout"
        method: "POST"
        servicePath: "/auth/logout"
        middlewares: ["auth"]

      - path: "/auth/profile"
        method: "GET"
        servicePath: "/auth/profile"
        middlewares: ["auth"]

  - name: kyc
    baseURL: "http://localhost:8081/api/v1"
    routes:
      - path: "/kyc/submit"
        method: "POST"
        servicePath: "/kyc/submit"
        middlewares: ["auth"]

      - path: "/kyc/user"
        method: "GET"
        servicePath: "/kyc/user"
        middlewares: ["auth"]

      - path: "/kyc/pending"
        method: "GET"
        servicePath: "/kyc-admin/pending"
        middlewares: ["auth"]

      - path: "/kyc/verify/:id"
        method: "POST"
        servicePath: "/kyc-admin/verify/:id"
        middlewares: ["auth"]
